src/objects/Hotel__c.object
<CustomObject>
    <description>Hotel information</description>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <description>Invoice for hotel reservation.</description>
    <fields>
        <fullName>Promo_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Promo Code</label>
        <referenceTo>Promo_Code__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Reservation__c</fullName>
        <label>Reservation</label>
        <referenceTo>Reservation__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{00000000}</displayFormat>
        <label>Invoice Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Promo_Code__c.object
<CustomObject>
    <description>Promotional Codes for bookings.</description>
    <fields>
        <fullName>Code__c</fullName>
        <label>Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Discount__c</fullName>
        <label>Discount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hotel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Hotel</label>
        <referenceTo>Hotel__c</referenceTo>
        <relationshipLabel>Promo Codes</relationshipLabel>
        <relationshipName>Promo_Codes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Promo Code</label>
    <nameField>
        <displayFormat>PC-{0000000}</displayFormat>
        <label>Promo Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Promo Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Reservation__c.object
<CustomObject>
    <description>Hotel Reservation record.</description>
    <fields>
        <fullName>Check_In__c</fullName>
        <label>Check In</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Check_Out__c</fullName>
        <label>Check Out</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Reservations</relationshipLabel>
        <relationshipName>Reservations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Promo_Code_Num__c</fullName>
        <label>Promo Code #</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Room__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Room</label>
        <referenceTo>Room__c</referenceTo>
        <relationshipLabel>Reservations</relationshipLabel>
        <relationshipName>Reservations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Reservation</label>
    <nameField>
        <displayFormat>RES-{000000000}</displayFormat>
        <label>Reservation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Room__c.object
<CustomObject>
    <description>Room details for a Hotel</description>
    <fields>
        <fullName>Hotel__c</fullName>
        <label>Hotel</label>
        <referenceTo>Hotel__c</referenceTo>
        <relationshipLabel>Rooms</relationshipLabel>
        <relationshipName>Rooms</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Room</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>Room Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rooms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestReservationTrigger.cls
@isTest
public class TestReservationTrigger {

    static testMethod void testCreateReservation() {
        // Create test user.
        List<User> adminUsers = TestUtil.createUsers(1, 'System Administrator');
        // Create Hotel data.
        List<Hotel__c> lHotels = TestDataUtil.createHotels(1);
        // Create Room data.
        List<Room__c> lRooms = TestDataUtil.createRooms(4, lHotels.get(0).Id);
        // Create Promo Code data.
        List<Promo_Code__c> lPromoCodes = TestDataUtil.createPromoCodes(2, lHotels.get(0).Id);
        // Create Contact data.
        List<Contact> lContacts = TestDataUtil.createContacts(2);

        System.runAs(adminUsers.get(0)) {
            // Assign perm set
            //TestUtil.addPermissionSet(adminUsers, 'Booking_Mgmt');
            Reservation__c oRes = new Reservation__c();
            oRes.Check_In__c = Date.today();
            oRes.Check_Out__c = Date.today().addDays(2);
            oRes.Contact__c = lContacts.get(0).Id;
            oRes.Promo_Code_Num__c = lPromoCodes.get(0).Code__c;
            oRes.Room__c = lRooms.get(0).Id;

            insert oRes;

            List<Invoice__c> lInvoices = [select Id,
                                                Discount__c,
                                                Promo_Code__c,
                                                Reservation__c,
                                                Total__c from Invoice__c
                                                where Reservation__c =: oRes.Id];

            System.assert(lInvoices.size() == 1, 'Number of invoices should be 1, created ' + lInvoices.size() + ' invoices.');
            System.assert(lInvoices.get(0).Discount__c == '$' + lPromoCodes.get(0).Discount__c, 'Discount is wrong.');
            System.assert(lInvoices.get(0).Promo_Code__c == lPromoCodes.get(0).Id, 'Promo Code was not correctly associated.');
            System.assert(lInvoices.get(0).Total__c == (2 * lRooms.get(0).Price__c - lPromoCodes.get(0).Discount__c), 'Total was not correctly calculated.');
        }

    }
}