src/objects/Session__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Speaker__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstName__c</fullName>
        <label>FirstName</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastName__c</fullName>
        <label>LastName</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Speaker</label>
    <nameField>
        <displayFormat>SPK-{000000000}</displayFormat>
        <label>Speaker Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataUtil.cls
@isTest
public class TestDataUtil {

    public static List<Session__c> createSessions(Integer iNum, Boolean sameDateTime) {
        List<Session__c> lResult = new List<Session__c>();
        DateTime sessionDate = DateTime.now();

        for (Integer i = 0; i < iNum; i++) {
            Session__c osession = new Session__c();
            osession.Name = 'Test ' + i;
            if (sameDateTime) {
               osession.Date__c = sessionDate;
            } else {
                osession.Date__c = sessionDate.addDays(i);
            }

            osession.Description__c = 'Test description';
            lResult.add(osession);
        }

        insert lResult;
        return lResult;
    }

    public static List<Speaker__c> createSpeakers(Integer iNum) {
        List<Speaker__c> lResult = new List<Speaker__c>();

        for(Integer i = 0; i < iNum; i++) {
            Speaker__c speaker = new Speaker__c();
            speaker.Email__c = 'testspeaker'+i+'@df16.test';
            speaker.FirstName__c = 'Tester';
            speaker.LastName__c = 'The ' + i;
            speaker.Title__c = 'Software Engineer';
            lResult.add(speaker);
        }

        insert lResult;
        return lResult;
    }

}