src/objects/Session__c.object
<CustomObject>
    <label>Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Session_Speaker__c.object
<CustomObject>
    <description>Junction object between Session and Speaker.</description>
    <fields>
        <fullName>Session__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Session</label>
        <referenceTo>Session__c</referenceTo>
        <relationshipLabel>Session Speakers</relationshipLabel>
        <relationshipName>Session_Speakers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Speaker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Speaker</label>
        <referenceTo>Speaker__c</referenceTo>
        <relationshipLabel>Session Speakers</relationshipLabel>
        <relationshipName>Session_Speakers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Session Speaker</label>
    <nameField>
        <displayFormat>SSPK-{00000000}</displayFormat>
        <label>Session Speaker Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Session Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Speaker__c.object
<CustomObject>
    <label>Speaker</label>
    <nameField>
        <displayFormat>SPK-{000000000}</displayFormat>
        <label>Speaker Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Speakers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestSessionSpeakerTrigger.cls
@isTest
public class TestSessionSpeakerTrigger {

    static testMethod void testCreateSessionSpeaker() {
        // Create test user.
        List<User> adminUsers = TestUtil.createUsers(1, 'System Administrator');
        // Create Session data.
        List<Session__c> lSessions = TestDataUtil.createSessions(2, false);
        // Create Speaker data.
        List<Speaker__c> lSpeakers = TestDataUtil.createSpeakers(1);

        System.runAs(adminUsers.get(0)) {
            //Create Session_Speaker__c
            Session_Speaker__c oSessSpeaker = new Session_Speaker__c();
            oSessSpeaker.Session__c = lSessions.get(0).Id;
            oSessSpeaker.Speaker__c = lSpeakers.get(0).Id;
            insert oSessSpeaker;

            //Verify record was successfully created.
            List<Session_Speaker__c> lsessionSpeakers = [select Id,
                                                            Session__c,
                                                            Speaker__c
                                                            from Session_Speaker__c
                                                            where Session__c = :lSessions.get(0).Id];

            System.assert(lsessionSpeakers.size() == 1, 'Number of Session Speaker records should be 1.');
            System.assert(lsessionSpeakers.get(0).Speaker__c == lSpeakers.get(0).Id, 'Speaker record does not match.');
        }

    }

    static testMethod void testCreateConflictingSessionSpeaker() {
        // Create test user.
        List<User> adminUsers = TestUtil.createUsers(1, 'System Administrator');
        // Create Session data.
        List<Session__c> lSessions = TestDataUtil.createSessions(2, true);
        // Create Speaker data.
        List<Speaker__c> lSpeakers = TestDataUtil.createSpeakers(1);
        //Create Session_Speaker__c
        Session_Speaker__c oSessSpeaker = new Session_Speaker__c();
        oSessSpeaker.Session__c = lSessions.get(0).Id;
        oSessSpeaker.Speaker__c = lSpeakers.get(0).Id;
        insert oSessSpeaker;

        System.runAs(adminUsers.get(0)) {
            try {
                Session_Speaker__c oSessSpeaker2 = new Session_Speaker__c();
                oSessSpeaker2.Session__c = lSessions.get(1).Id;
                oSessSpeaker2.Speaker__c = lSpeakers.get(0).Id;
                insert oSessSpeaker2;
            } catch (Exception e) {
                System.assert(e.getMessage().contains('The speaker is already booked at that time.'));
            }
        }
    }

}